--Insert data English Quiz 
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(1,"You are old enough to take ____for what you have done.","B","responsible","responsibility","responsibly","irresponsible",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(2,"John is____only child in his family so his parents love him a lot.","C","a ","an","the","no article",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(3,"According to the boss, John is the most____for the position of executive secretary.","C","supportive","caring","suitable","comfortable",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(4,"What are the____of that country? - I think it is some kinds of cheese and sauces.","D","drinks","beverages","grains","special dishes",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(5,"In the last hundred years, traveling____much easier and more comfortable.","C","becomes","has become","became","will become",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(6,"How many Golden Ball award does Lionel Messi have?","D","5","4","2","6","h6");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(7,"What tool is this?","B","iron","vacuum cleaner","radiator","blinds","h7");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(8,"What is Japanese traditional costume?","C","Ao Dai","Hanbok","Kimono","Sari","h8");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(9,"This is the capital of which country?","C","Japan","China","France","Taiwan","h9");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(10,"Who is this?","B","Roger Fedeger","Rafael Nadal","Novak Djokovic","Andy Murray","h10");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(11,"What city is this?","A","Moscow","Dhaka","Istanbul","Karachi","h11");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(12,"What country's traditional costume is this?","C","China","Taiwan","Vietnam","Hongkong","h12");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(13,"What football stadium is this?","A","Old Trafford","Camp Nou","Emirates","Santiago Bernabeu","h13");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(14,"In my opinion, family members are responsible for____.","D","the housework","the chores","homework","A and B",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(15,"My grandpa is the most conservative person in my family. He never____about way of life.","B","gives his opinion","changes his mind","gives his view","keeps in mind",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(16,"After graduating from university, I want to____my father's footsteps.","A","follow in","succeed in","go after","keep up",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(17,"In a nuclear family, both mother and father have responsibility for housekeeping and____.","C","child care","homework","childcare","generation gap",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(18,"I suggest that Peter____the directions carefully before assembling the bicycle.","A","read","reading","reads","to read",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(19,"We request that she____the window.","B","not open","not to open","not opening","to not open",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(20,"The UK is considering the proposal that it____compensations for damages of the Indian embassy.","D","been paying","is paying","paid","pay",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(21,"Those companies were 'CLOSED' due to some seriously financial problems.","C","taken off","put away","go under","gone over",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(22,"For environmental safety, we need to find ways to reduce 'EMISSION' of fumes and smoke of factories.","B","leak","release","poison","pollutant",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(23,"Nylon is a 'MAN-MADE' fibre, the use of which has helped more people to have cheaper and more colourful clothes to wear.","D","natural","plastic","synthetic","artificial",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(24,"The advances of commercial airplanes resulted in a 'SHRINKING' world.","C","decreasing","reduced","smaller","compressing",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(25,"We have to suffer from traffic 'CONGESTION' and pollution every day.","D","accident","fullness","mass","crowded",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(26," I saw Charlie_____through the traffic toward me","C","sprinting","hiking","sprinting or running","running",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(27,"What is the name of this band?","A","OneRepublic","One Direction","The Beatles","HKT","h27");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(28,"What is this famous statue called?","D","Statue of Unity","Ushiku Daibutsu","Sendai Daikannon","Statue of Liberty","h28");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(29,"What are they playing?","D","They're playing socccer","They're playing tennis","They're playing basketball","They're playing soccer","h29");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(30,"Which country owns this flag?","B","Spain","Netherlands","Vietnam","Laos","h30");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(31,"What does the symbol in the picture represent for?","B","Javascript","HTML5","CSS","SCSS","h31");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(32,"Where is this place?","C","Bangkok","Thailand","Laos","Singapore","h32");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(33,"When did Leonardo Dicaprio win oscar?","B","2015","2016","2017","2020","h33");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(34,"How many Golden Ball awards does Cristiano Ronaldo have?","B","4","5","6","7","h34");
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(35,"The old man_____to go somewhere else to play football.","B","said the kids","told the kids","told to the kids","spoke to the kids",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(36,"The new stadium_____next June.","A","will be finished","was finished","is going finished","has been finished",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(37," Go out without a coat____you are sure to catch a cold.","D","for","but","if","and",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(38,"I have given you the money back,___?","B","don't I","haven't I","won't I","isn't it",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(39,"Something must have happened to them. I can hear___.","A","them shout","that they shout","they shout","them to shout",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(40,"Neither Kelly nor her friends____at the airport yesterday","B","are","were","is","was",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(41,"He was not allowed to go to the playground____he played truant yesterday.","B","so","as","or","but",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(42,"The price of vegetables____gone up recently due to the bad weather.","D","have","having","had","has",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(43,"The sky is filled with many dark clouds. It looks like it____rain.","B","must","might","shall","should",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(44,"Each student___given a postcard on New Year Day.","D","will","were","are","was",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(45,"The chemist has_______the odds and found a cure for this rare disease.","B","decried","defied","Disallowed","denied",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(46," I_________by when I noticed a suspicious looking woman near your car.","B","am driving","was driving","had been driven","drove",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(47,"Many of the guests at a party were______by the host's drunken behavior.","C","disgust","disgusting","disgusted","being disgusted",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(48," Jean is________friend that I would trust her with my life.","B","a so good","so good a","such good","a such good",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(49,"Harry has been causing problems_____the whole class lately.","C","by","with","for","to",null);
Insert into "EnglishQuiz"(ID,Question,Result,AnswerA,AnswerB,AnswerC,AnswerD,Image)VALUES(50,"These cars date back_______.","D","1930s","in 1930s","to the 1930s","at the 1930s",null);

--Insert data Correct Word
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(1,"c a t","cat",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(2,"d o g","dog",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(3,"r u n","run",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(4,"n u n","nun",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(5,"n o n e","none",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(6,"c a r","car",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(7,"p e n","pen",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(8,"c u p","cup",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(9,"b a t","bat",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(10,"a d d","add",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(11,"a i r","air",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(12,"a s k","ask",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(13,"a g e","age",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(14,"b a g","bag",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(15,"b e d","bed",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(16,"e a r","ear",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(17,"c r a b","crab",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(18,"c o w","cow",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(19,"s t a r","star",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(20,"t r e e","tree",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(21,"p l a n t","plant",1);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(22,"w i n d","wind",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(23,"s a n d","sand",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(24,"l e a v e","leave",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(25,"f l o w e r","flower",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(26,"b i r d s","birds",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(27,"t o o l s","tools",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(28,"g r a s s","grass",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(29,"r u l e r","ruler",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(30,"g l a s s","glass",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(31,"p h o n e","phone",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(32,"b o o k","book",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(33,"s o c k s","socks",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(34,"u g l y","ugly",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(35,"c h a i r","chair",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(36,"t a b l e","table",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(37,"l a m p","lamp",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(38,"a l b u m","album",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(39,"b a r k","bark",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(40,"s l i p p e r s","slippers",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(41,"s c i s s o r s","scissors",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(42,"m o u s e","mouse",2);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(43,"b e a u t i f u l","beautiful",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(44,"a d v a n c e","advance",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(45,"a c t u a l l y","actually",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(46,"a p a r t m e n t","apartment",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(47,"a s s i s t a n t","assistant",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(48,"a t t r a c t i v e","attractive",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(49,"b e l i e v e","believe",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(50,"b i s c u i t","biscuit",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(51,"b l a c k b o a r d","blackboard",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(52,"b a t h r o o m","bathroom",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(53,"b o o k s h e l f","bookshelf",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(54,"c o m f o r t a b l e","comfortable",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(55,"p e r f o r m","perform",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(56,"p e r s o n","person",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(57,"p o p u l a t i o n","population",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(58,"q u o t e","quote",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(59,"c o d e","code",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(60,"d e c a d e","decade",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(61,"g a m e","game",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(62,"s o c c e r","soccer",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(63,"v o l l e y b a l l","volleyball",3);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(64,"a c c u r a t e","accurate",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(65,"c o n v i n c e","convince",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(66,"c u r r e n c y","currency",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(67,"s w i m m i n g","swimming",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(68,"d o m i n o e s","dominoes",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(69,"b a d m i n t o n","badminton",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(70,"n e w s p a p e r","newspaper",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(71,"p a r a g r a p h","paragraph",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(72,"p l a y g r o u n d","playground",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(73,"c i r c u l a t i o n","circulation",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(74,"s i g h t s e e i n g","sightseeing",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(75,"s e n t e n c e","sentence",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(76,"s k a t e b o a r d","skateboard",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(77,"s n o w b o a r d","snowboard",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(78,"s u c c e s s f u l","successful",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(79,"t e m p e r a t u r e","temperature",4);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(80,"c o n g r a t u l a t i o n","congratulation",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(81,"c o n v e r s a t i o n","conversation",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(82,"e x a m i n a t i o n","examination",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(83,"i n t e r n a t i o n a l l y","internationally",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(84,"n a t i o n a l i t y","nationality",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(85,"d e v e l o p m e n t","development",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(86,"r e c e p t i o n i s t.","receptionist",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(87,"q u a l i f i c a t i o n","qualification",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(88,"r e s t a u r a n t","restaurant",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(89,"r o u n d a b o u t","roundabout",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(90,"e c o n o m y","economy",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(91,"c o m p l i c a t e d","complicated",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(92,"c o r r e s p o n d i n g","corresponding",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(93,"s n o r k e l l i n g","snorkelling",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(94,"s p o t l i g h t","spotlight",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(95,"p h o t o g r a p h e r","photographer",5);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(96,"e n v i r o n m e n t a l l y","environmentally",6);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(97,"r e s p o n s i b i l i t y","responsibility",6);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(98,"t r a n s p o r t a t i o n","transportation",6);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(99,"a c k n o w l e d g e m e n t","acknowledgement",6);
Insert into "CorrectWord"(ID,Word,Key,Level)VALUES(100,"s p e c i a l i z a t i o n","specialization",6);
--Insert HighScoreCorrectWord
Insert into "HighScoreCorrectWord"(Top,Name,Star)VALUES(1,"Your Name1",0);
Insert into "HighScoreCorrectWord"(Top,Name,Star)VALUES(2,"Your Name2",0);
Insert into "HighScoreCorrectWord"(Top,Name,Star)VALUES(3,"Your Name3",0);
Insert into "HighScoreCorrectWord"(Top,Name,Star)VALUES(4,"Your Name4",0);
Insert into "HighScoreCorrectWord"(Top,Name,Star)VALUES(5,"Your Name5",0);
--Insert HighScoreCorrectWord
Insert into "HighScoreEnglishQuiz"(Top,Name,Score)VALUES(1,"Your Name1",0);
Insert into "HighScoreEnglishQuiz"(Top,Name,Score)VALUES(2,"Your Name2",0);
Insert into "HighScoreEnglishQuiz"(Top,Name,Score)VALUES(3,"Your Name3",0);
Insert into "HighScoreEnglishQuiz"(Top,Name,Score)VALUES(4,"Your Name4",0);
Insert into "HighScoreEnglishQuiz"(Top,Name,Score)VALUES(5,"Your Name5",0);